#!/usr/bin/env python3
"""Reconcile all source logs, measured repeats, precision, and paper scope."""
import csv,hashlib,json,math,pathlib,re,statistics,subprocess,sys
root=pathlib.Path('/home/huangjianqiang_group/hdacp1/data/wzh/GCN-extra')
run=pathlib.Path(sys.argv[1]);build=pathlib.Path(sys.argv[2]);asset=pathlib.Path(sys.argv[3])
complete=json.loads((run/'completion.json').read_text());assert complete==dict(passed=17,excluded=8,failed=0,mode='formal')
assert (run/'exit_status.txt').read_text().strip()=='0'
rows=list(csv.DictReader((run/'summary.csv').open()))
assert len(rows)==17 and len({x['graph'] for x in rows})==17
for x in rows:
 assert x['pass']=='1' and float(x['relative_L2'])<.03 and float(x['normalized_max'])<.03
 states=json.loads((run/x['graph']/'status.json').read_text());assert states['status']=='PASS'
 for label in ['correctness','e2e','tfs_kernel','mkl_kernel']:
  assert json.loads((run/x['graph']/(label+'.status.json')).read_text())['returncode']==0
  log=(run/x['graph']/(label+'.log')).read_text()
  if label!='correctness':assert len(re.findall(r'\s+run \d+:',log))==(10 if label=='e2e' else 5)
def gm(values):return math.exp(sum(math.log(v) for v in values)/len(values))
historical={};name=None;section=None
for line in (build/'reference_logs/gcn_e2e_v3_all_4624352.log').read_text().splitlines():
 m=re.match(r'# ([\w-]+)$',line)
 if m:name=m[1];historical[name]={}
 m=re.search(r'TFS V3 E2E BEST: ([0-9.]+) ms',line)
 if m and name:historical[name]['tfs_ms']=float(m[1])
 m=re.search(r'MKL E2E BEST: ([0-9.]+) ms',line)
 if m and name:historical[name]['mkl_ms']=float(m[1])
mapping=[]
for x in rows:
 h=historical[x['graph']];assert abs(h['tfs_ms']-float(x['paper_tfs_e2e_ms']))<.6 and abs(h['mkl_ms']-float(x['paper_mkl_e2e_ms']))<.6
 mapping.append(dict(graph=x['graph'],paper_tfs_ms=float(x['paper_tfs_e2e_ms']),historical_tfs_ms=h['tfs_ms'],paper_mkl_ms=float(x['paper_mkl_e2e_ms']),historical_mkl_ms=h['mkl_ms'],source_log_statistic='minimum of 5, not median'))
(run/'paper_table_to_historical_log.json').write_text(json.dumps(mapping,indent=2))
stats=dict(completion=complete,node=(run/'node.txt').read_text().strip(),all17_kernel_min_gmean=gm([float(x['kernel_min_speedup']) for x in rows]),all17_e2e_min_gmean=gm([float(x['e2e_min_speedup']) for x in rows]),all17_kernel_median_gmean=gm([float(x['kernel_median_speedup']) for x in rows]),all17_e2e_median_gmean=gm([float(x['e2e_median_speedup']) for x in rows]),e2e_faster=sum(float(x['e2e_min_speedup'])>1 for x in rows),paper_winner15_e2e_min_gmean=gm([float(x['e2e_min_speedup']) for x in rows if float(x['paper_e2e_speedup'])>1]),max_final_bf16_relative_L2=max(float(x['relative_L2']) for x in rows),max_final_bf16_normalized_max=max(float(x['normalized_max']) for x in rows),paper_timing_baseline='unmodified gcn_e2e_v3.cpp',prior_older_source='gcn_e2e_bench.cpp; previous claim about paper original TFS slower is withdrawn',paper_full25_reproduction=False,reason='17 numerically comparable graphs reproduced. Six nonunit CSR graphs have unequal source operators; two graphs exceed original LP64 safe limits.')
(run/'audit_summary.json').write_text(json.dumps(stats,indent=2)+'\n')
with (run/'slurm_accounting.txt').open('w') as out:
 subprocess.run(['sacct','-j',run.name.split('-')[-1],'-o','JobID,JobName,Partition,NodeList,State,ExitCode,Elapsed,AllocCPUS,MaxRSS','-P'],stdout=out,check=True)
doc=['# TFS paper reproduction: corrected source version (2026-10-04)','',
'## Conclusion and correction','',
'Paper Table 2 is generated by `gcn_e2e_v3.cpp` (FP32 intermediate + BF16 final), not the older `gcn_e2e_bench.cpp` (FP32 final with redundant global output zeroing). Its historical log `gcn_e2e_v3_all_4624352.log` matches all 17 eligible table entries, allowing for rounded seconds in the paper. The earlier 0.891x aggregate result refers to the older source version only; using it to conclude that the paper TFS is slower than MKL was incorrect. That inference is withdrawn. Old evidence is preserved.','',
'The original v3 source also removes global output memset and changes output storage and loop organization. The version difference must not be attributed solely to BF16 output, NUMA, or the reduction extension. Current reduction candidates have not yet been compared against this paper v3 baseline.','',
'## Paper and source provenance','',
'Title: *TFS: Tile-Aware SpMM–GeMM Fusion for Accelerating GNN Inference on Intel AMX*. DOI: https://doi.org/10.1145/3832810.3832855 . Public primary conference program: https://icpp2026.github.io/schedule/ . The local Chinese manuscript `D:/Apaper/GAT/TFS_Tile_Aware_SpMM_GeMM_Fusion_AMX_中文版.md` supplies the paper numbers. Public ACM full-text/PDF access failed in this session; this report does not claim inspection of the final published English PDF. Historical source logs independently identify the table-producing code.','',
'Build: `'+str(build)+'`. Source snapshots and their hashes are immutable there; all three raw performance sources are byte-identical to read-only `yx/TFS/code`. Compile flags match source compile scripts, icpx 2024.1.0, MKL 2023.2.0, LP64.','',
'## Current runtime and measurement','',
'Formal job '+run.name.split('-')[-1]+' on '+stats['node']+', partition intel_expr, one exclusive node, 32 OpenMP threads, OMP_PROC_BIND=close, OMP_PLACES=cores. No added numactl/interleave, MKL thread override, sparse hint alteration, or random-input replacement. K=128, R=64, TR=16, ascending DegreeSort. Observed topology, memory policy, environment, and linked libraries are saved. CPU is Xeon Max 9462; current HBM cache mode is not independently proven by this run.','',
'One warmup and five measured repetitions exactly as raw sources implement. Prepared E2E includes both GCN layers, ReLU, and interlayer BF16 conversion; loading, sorting, initial H conversion, and W packing are outside this interval. This is computational inference flow, not a trained classification model.','',
'## Per-graph results','',
'Minimum of five below, matching the historical source BEST values. Median ratios are also reported because the manuscript describes medians.','',
'| Graph | Paper kernel speedup | New kernel speedup | Paper E2E speedup | New TFS E2E ms | New MKL E2E ms | New E2E speedup | Median E2E speedup |',
'|---|---:|---:|---:|---:|---:|---:|---:|']
for x in rows:
 doc.append('| '+x['graph']+' | '+f"{float(x['paper_kernel_speedup']):.2f}x | {float(x['kernel_min_speedup']):.2f}x | {float(x['paper_e2e_speedup']):.2f}x | {float(x['tfs_e2e_min_ms']):.2f} | {float(x['mkl_e2e_min_ms']):.2f} | {float(x['e2e_min_speedup']):.2f}x | {float(x['e2e_median_speedup']):.2f}x |")
doc += ['',f"All 17: kernel minimum-ratio geometric mean {stats['all17_kernel_min_gmean']:.3f}x; E2E {stats['all17_e2e_min_gmean']:.3f}x. TFS wins {stats['e2e_faster']}/17 on E2E. Median-ratio E2E geometric mean {stats['all17_e2e_median_gmean']:.3f}x.",'',
f"Using the paper's 15 winning E2E graphs only, new geometric mean {stats['paper_winner15_e2e_min_gmean']:.3f}x, compared with the manuscript's 2.18x. Do not describe a winners-only average as the full 17/25 average. The paper's 24-case kernel aggregate 2.21x has not been fully revalidated here.",'',
'## Numerical evidence and source discrepancies','',
'Separate validator runs before raw timed executables on every graph. It checks the actual final BF16 output against the original FP32 MKL output over every element, reporting max_abs_error, mean_abs_error, relative_L2_error, and max_abs_error/max_abs_reference. Gate is 0.03 for both relative L2 and normalized max; this is numerical agreement, not classification accuracy. The raw performance executables are untouched.','',
f"17/17 full BF16-output checks pass. Maximum relative L2 {stats['max_final_bf16_relative_L2']:.6f}; maximum normalized max {stats['max_final_bf16_normalized_max']:.6f}. See per-graph correctness.log and summary.csv.",'',
'The historical E2E precision function uses max_abs_error/max_abs_reference, while the manuscript presents a Frobenius relative error. The source precision block additionally reruns the final layer as FP32 output, although its timed final layer outputs BF16. Those historical checks therefore do not directly validate the timed final BF16 result. This run supplies that missing check separately.','',
'The manuscript says median of five, but raw sources print BEST=min of five, and all eligible Table 2 values match the historical BEST entries. Both minimum and median are retained without silently relabeling either.','',
'## Coverage limits','',
'25 graph entries reconciled: 17 PASS; six excluded for nonunit CSR values because original TFS ignores values while MKL uses them (cage15, FullChip, kron_g500-logn21, rajat31, scircuit, sx-stackoverflow); two excluded for original LP64 limits (Friendster edge offsets, road_usa dense offsets). These are explicit coverage limits. Unequal operators on the six weighted matrices must not be classified merely as BF16 instability. No original CSR values are changed.','',
'## Real features and weights under yx','',
'Fresh inventory: `'+str(asset/'inventory.json')+'`. 51 tensor/data archives inspected by filename/metadata, without executing pickle. Reddit FP32 features: `yx/TFS/journal_rethink_20260914/pmu_20260915/data_dgl_reddit/graphsaint_bundle/feats.npy`, shape (232965,602); GraphSAINT also has FP64 features with the same shape. Products: `yx/TFS/journal_rethink_20260914/ar_ab_20260915/datasets_reordered/ogbn_products_natural_copy.pt`, a graph/features/labels package (known x shape 2449029x100), not a trained checkpoint. Eight `w0_after_step1.npy` snapshots have shape 100x128 FP32, single training-step debug outputs. No complete trained checkpoint was identified in this TFS-tree inventory; this is not proof of absence elsewhere under yx.','',
'Original paper source benchmarks create H, W1, W2 with srand(12345), 128-dimensional features, and random 128x128 weights. They do not read real input features or checkpoints. To reproduce those numbers, this run preserves that source-defined input. A real-feature/checkpoint classification experiment requires its own shape, normalization, class count, node order, and accuracy protocol.','',
'## Evidence and reproduction commands','',
'- Main raw run: `'+str(run)+'`.',
'- `summary.csv`, `raw_repeats.csv`, `suite_status.json`, `audit_summary.json`, and `paper_table_to_historical_log.json`.',
'- Per graph: `correctness.log`, `e2e.log`, `tfs_kernel.log`, `mkl_kernel.log`, exact argv and exit statuses.',
'- Build: `bash scripts/build_paper_reproduction.sh`.',
'- Shared correctness: `bash scripts/submit_paper_reproduction.sh smoke`.',
'- Exclusive formal: `bash scripts/submit_paper_reproduction.sh formal`.',
'- Immutable launcher snapshots prevent modification of live jobs.',
'- GCN-extra handoffs record build, both submissions, smoke/formal completion, asset audit, and this reconciliation.','']
target=root/'docs/PAPER_REPRODUCTION_RESULTS_20261004.md';target.write_text('\n'.join(doc))
e=dict(id='paper-reconciliation-20261004-10864848',kind='paper_reproduction_reconciliation',status='PASS',evidence=str(run),report=str(target),statistics=stats,paper_eligible=True,issues='Correct source version reproduces major paper speedups; prior conclusion about paper original TFS slower withdrawn. Historical min/median and FP32-check/BF16-timed output discrepancies explicitly audited.',next='Any reduction extension must first rebase on this gcn_e2e_v3 baseline, with the same BF16 final output and source MKL; trained-checkpoint inference remains a separate task.')
(run/'reconciliation.event.json').write_text(json.dumps(e,indent=2))
subprocess.run(['python3',str(root/'scripts/record_event.py'),str(run/'reconciliation.event.json')],check=True)
print(json.dumps(stats,indent=2))
